(async function () {
  const tableBody = document.getElementById("spreads-body");
  
  function fmt(n, d = 1) {
    return (n == null || isNaN(n)) ? "N/A" : Number(n).toFixed(d);
  }

  try {
    // Fetch the JSON generated by your Signal.py script

    const res = await fetch("/data/spreads.json", { cache: "no-store" });
    let signals = await res.json();


    if (!Array.isArray(signals) && signals.data) {
        signals = signals.data;
    }
    
    // Sort by Market Cap (Highest first)
    signals.sort((a, b) => (b.mcap || 0) - (a.mcap || 0));

    tableBody.innerHTML = signals.map(s => `
      <tr class="${s.type}">
        <td><strong>${s.ticker}</strong></td>
        <td>${fmt(s.mcap, 1)}B</td>
        <td>$${fmt(s.price, 2)}</td>
        <td>${fmt(s.rsi, 1)}</td>
        <td>${fmt(s.adx, 1)}</td>
        <td>
          <span class="badge ${s.strategy.includes('Debit') ? 'debit' : 'credit'}">
            ${s.strategy}
          </span>
        </td>
        <td>
          ${s.is_squeeze 
            ? '<span class="text-warning">⚠️ Squeeze (Avoid)</span>' 
            : '<span class="text-success">✅ Volatility OK</span>'}
        </td>
      </tr>
    `).join("");
  } catch (e) {
    console.error("Failed to load spreads:", e);
    tableBody.innerHTML = `<tr><td colspan="7">No candidates found or error loading data.</td></tr>`;
  }
})();
