name: Scheduled Trading Bot Run

on:
  schedule:
    - cron: '30 13-20 * * 1-5'  # Runs hourly from 6:30AM to 1:30PM PDT (Mon-Fri)
  workflow_dispatch:            # Allows you to run it manually

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Trading Bot
        run: python rsiiv.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
