name: RSI Backtest

on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * *'  # Every day at 5:30 AM PT (adjust to your preferred time)

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ta openpyxl

      - name: Run RSI backtest
        run: python rsi_backtest.py

      - name: Upload backtest output
        uses: actions/upload-artifact@v4
        with:
          name: rsi-backtest-results
          path: stock_backtest_PNL.xlsx
