name: Scheduled Signal Processing

on:
  schedule:
    # 5:30 AM PT (12:30 UTC)
    - cron: '30 12 * * *'
    # 6:30am PT = 13:30 UTC
    - cron: '30 13 * * *'
    # Hourly from 7:30 AM to 12:30 PM PT (2:30 PM to 7:30 PM UTC)
    - cron: '30 14-19 * * *'  



jobs:

  pe_rsi_filter:
    if: contains(github.event.schedule, '0 12 * * *')
    runs-on: ubuntu-latest
    outputs:
      filtered-tickers: ${{ steps.filter.outputs.filtered }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PE and RSI filter script
        id: filter
        run: |
          # Run your filtering script that outputs filtered tickers into an output file
          python scripts/filter_pe_rsi.py --output filtered_tickers.txt
          # Pass filtered list back to job output
          echo "::set-output name=filtered::$(cat filtered_tickers.txt | tr '\n' ',')"

  signal_first_run:
    if: contains(github.event.schedule, '30 13 * * *')
    needs: pe_rsi_filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Signal.py on filtered tickers and send first email
        run: |
          python Signal.py --tickers "${{ needs.pe_rsi_filter.outputs.filtered }}" --email-type first

  signal_second_run:
    if: contains(github.event.schedule, '31 13 * * *')
    needs: pe_rsi_filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Signal.py on remaining tickers and send second email if new buys
        run: |
          # Compute rest of tickers by excluding filtered tickers
          python scripts/run_signal_for_rest.py --excluded "${{ needs.pe_rsi_filter.outputs.filtered }}" --email-type second

  hourly_signal_check:
    if: startsWith(github.event.schedule, '0 ') && !contains(github.event.schedule, '12') && !contains(github.event.schedule, '13')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Signal.py on all tickers and send email if new buys
        run: |
          python Signal.py --email-type hourly
