name: Scheduled Signal Processing
on:
  schedule:
    # 5:30 AM PT (12:30 UTC)
    - cron: '30 12 * * 1-5'
    # 6:30 AM PT (13:30 UTC) - for filtered tickers
    - cron: '30 13 * * 1-5'
    # 6:31 AM PT (13:31 UTC) - for remaining tickers
    - cron: '31 13 * * 1-5'
    # Hourly from 7:30 AM to 12:30 PM PT (14:30 to 19:30 UTC)
    - cron: '30 14 * * 1-5'
    - cron: '30 15 * * 1-5'
    - cron: '30 16 * * 1-5'
    - cron: '30 17 * * 1-5'
    - cron: '30 18 * * 1-5'
    - cron: '30 19 * * 1-5'
  workflow_dispatch:

jobs:
  pe_rsi_filter:
    runs-on: ubuntu-latest
    outputs:
      filtered-tickers: ${{ steps.filter.outputs.filtered }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run PE and RSI filter script (or create dummy for testing)
        id: filter
        run: |
          # For testing - create a dummy filtered list if script doesn't exist
          if [ -f "scripts/filter_pe_rsi.py" ]; then
            python scripts/filter_pe_rsi.py --output filtered_tickers.txt
          else
            echo "AAPL,MSFT,GOOGL" > filtered_tickers.txt
          fi
          echo "filtered=$(cat filtered_tickers.txt | tr '\n' ',')" >> $GITHUB_OUTPUT

  signal_filtered_run:
    needs: pe_rsi_filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Signal.py on filtered tickers and send first email
        run: |
          python Signal.py --tickers "${{ needs.pe_rsi_filter.outputs.filtered-tickers }}" --email-type first

  signal_all_run:
    needs: signal_filtered_run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Signal.py on all tickers and send second email if new buys
        run: |
          python Signal.py --email-type second

  hourly_signal_checks:
    if: contains(fromJson('["30 14 * * 1-5","30 15 * * 1-5","30 16 * * 1-5","30 17 * * 1-5","30 18 * * 1-5","30 19 * * 1-5"]'), github.event.schedule)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Signal.py on all tickers for hourly check and send email if new buys
        run: |
          python Signal.py --email-type hourly
