# GitHub Actions workflow to run Signal3.py (Trading Bot)
# This workflow installs dependencies, runs the bot, and saves artifacts.

name: Trading Bot Run

#on:
  #schedule:
    - cron: '30 13 * * 1-5'
    - cron: '30 14 * * 1-5'
    #- cron: '30 15 * * 1-5'
    #- cron: '30 16 * * 1-5'
    #- cron: '30 17 * * 1-5'
    - cron: '30 18 * * 1-5'
    #- cron: '30 19 * * 1-5'
    #- cron: '30 20 * * 1-5'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Running Signal3.py (Trading Bot)
      - name: Run Trading Bot (Signal4.py)
        #run: python Signal3.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

      - name: List puts_data folder contents (debug)
        run: ls -la puts_data || echo "No puts_data folder found"

      - name: Upload buy_signals.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: buy-signals
          path: buy_signals.txt

      - name: Upload puts_data artifact
        uses: actions/upload-artifact@v4
        with:
          name: puts-data-json
          path: puts_data
