name: Signals

on:
  schedule:
    - cron: '30 13 * * 1-5'
    - cron: '30 14 * * 1-5'
    #- cron: '30 15 * * 1-5'
    #- cron: '30 16 * * 1-5'
    #- cron: '30 17 * * 1-5'
    - cron: '30 18 * * 1-5'
    #- cron: '30 19 * * 1-5'
    #- cron: '30 20 * * 1-5'
  workflow_dispatch:

jobs:
  run-signals:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    env:
      PYTHONUNBUFFERED: "1"
      STATE_DIR: state
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Restore cache folder for data, logs, state (optional)
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            data
            logs
            state
          key: signal-state-${{ runner.os }}-latest
          restore-keys: |
            signal-state-${{ runner.os }}-

      # Download previously uploaded artifacts (CSV files, etc.) if any (optional)
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: signals-outputs
          path: ./ # or specify subdir

      - name: Run Trading Bot
        run: python Signal3.py

      - name: Ensure folders exist
        run: |
          mkdir -p data logs state

      # Upload updated CSV files, logs, state as artifacts for next runs
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: signals-outputs
          path: |
            data
            logs
            state

      # Save updated cache (optional)
      - name: Save updated cache
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            data
            logs
            state
          key: signal-state-${{ runner.os }}-${{ github.run_id }}
